### ISSUE TITLE
error: ‘vf2_subgraph_mono’ is not a member of ‘boost’

### ISSUE THREAD

**Issue by RansSelected** [idea-iitd/graphgen#1]
Hi! I'm trying to make the code up and running, but unfortunately I have this kind of error  while  ./build.sh execution :

```
metrics/isomorph.cpp: In function ‘bool is_subgraph_isomorphic(Graph, Graph)’:
metrics/isomorph.cpp:54:16: error: ‘vf2_subgraph_mono’ is not a member of ‘boost’
     bool res = boost::vf2_subgraph_mono(smallGraph, bigGraph, callback, boost::vertex_order_by_mult(smallGraph),
                ^
metrics/unique.cpp: In function ‘bool is_subgraph_isomorphic(Graph, Graph)’:
metrics/unique.cpp:52:16: error: ‘vf2_subgraph_mono’ is not a member of ‘boost’
     bool res = boost::vf2_subgraph_mono(smallGraph, bigGraph, callback, boost::vertex_order_by_mult(smallGraph),
                ^
```

Do you have any ideas why it could happen? Maybe a specific version of boost is needed to use?

**Comment by nikhil10sep** [comment]
You need to update the boost library include path in the build.sh file. Currently, it's set to $HOME/boost/include

**Comment by RansSelected** [comment]
> You need to update the boost library include path in the build.sh file. Currently, it's set to $HOME/boost/include

Hi! Thank you for your answer. I changed the **build.sh**  file, now it looks like this :

```
mkdir -p bin

g++ -std=c++11 dfscode/dfs_code.cpp -o bin/dfscode -O3
g++ -std=c++11 metrics/orca/orca.cpp -o bin/orca -O3
g++ -std=c++11 metrics/isomorph.cpp -O3 -o bin/subiso -fopenmp -I/usr/include/boost
g++ -std=c++11 metrics/unique.cpp -O3 -o bin/unique -fopenmp -I/usr/include/boost
```

But the problem remains the same. I run everything on AWS, via jupyter notebook and terminal.

**Comment by nikhil10sep** [comment]
All C++ binaries are saved under the **graphgen/bin/** path. Make sure you run **build.sh** in the root directory of the project. 

Try to compile the following sample C++ boost program. Save it to file named **example.cpp**

```
#include "boost/lambda/lambda.hpp"
#include <iostream>
#include <iterator>
#include <algorithm>

int main()
{
    using namespace boost::lambda;
    typedef std::istream_iterator<int> in;

    std::for_each(
        in(std::cin), in(), std::cout << (_1 * 3) << " " );
}
```

Use this compile it: `g++ -I /usr/include/boost example.cpp -o example` and share the compilation result.

Also, we used **boost version 1.70**

**Comment by RansSelected** [comment]
> g++ -I /usr/include/boost example.cpp -o example

I have no compilation results... when I run  `./example`, no results are shown - terminal just got stuck.
I have boost version: 1.53.0

**Comment by nikhil10sep** [comment]
Boost version **1.53.0** doesn't support `vf2_subgraph_mono` routine used in `isomorph.cpp` and `unique.cpp`. 
Please update your boost to 1.70 version or higher.

`subiso` and `unique` binaries are built by `build.sh` which is falling in your case.
You can ignore this and go ahead with your training. `subiso` and `unique` are only required for evaluating the novelity and uniqueness metrics when comparing the generated graphs with test graphs. These binaries aren't required for training.
