### ISSUE TITLE
How to run the code with gpu support?

### ISSUE THREAD

**Issue by RansSelected** [idea-iitd/graphgen#2]
Hi! I have a problem running the training with GPU. I've installed cuda 10.0, which is compatible with my hardware. Anyways to troubleshoot?
I'll appreciate your help.

**Comment by nikhil10sep** [comment]
There is a field for **device** in `args.py`
````
self.device = torch.device(
            'cuda:0' if torch.cuda.is_available() else 'cpu')
````

So if `torch.cuda.is_available()` evaluates to **True** the code will run on GPU.
You can print `args.device` in the starting of the `main.py` file to check on which device is the code actually running.

**Comment by RansSelected** [comment]
> There is a field for **device** in `args.py`
> 
> ```
> self.device = torch.device(
>             'cuda:0' if torch.cuda.is_available() else 'cpu')
> ```
> 
> So if `torch.cuda.is_available()` evaluates to **True** the code will run on GPU.
> You can print `args.device` in the starting of the `main.py` file to check on which device is the code actually running.

Thanks a lot! It helps, I had a problem with notebook instance on AWS, now solved.
