### ISSUE TITLE
Whats the 'degree' and 'CC' options in ENZYMES dataset?

### ISSUE THREAD

**Issue by Xiaohui9607** [idea-iitd/graphgen#6]
Hi, I am planning to move all the real datasets from graphRNN to your implementation, and there is an option (degree/cc) I am a little confused, can you point me out what it is?

**Comment by nikhil10sep** [comment]
The degree and CC options are the vertex invariants used to augment existing node labels by appending degree or the clustering coefficient (CC). Checkout section 4.4 in the paper for detailed discussion.
