### ISSUE TITLE
Someone I can get in contact with?

### ISSUE THREAD

**Issue by Omatikaya123** [idea-iitd/graphgen#8]
Thank you so much for this git! However, I'm experiencing a lot of errors. Is there someone who I can get in contact with that has run/edited this library on/for windows? My hunch is that this is made in Linux. 

Cheers, Oma.

**Comment by harshvjain** [comment]
Sorry for late response, and yes all the code and testing has been done on Linux.

Happy Hunting
Harsh, Co-auther GraphGen
