### ISSUE TITLE
KeyError: 'hv' in baselines/dgmg/model.py

### ISSUE THREAD

**Issue by rkondo3** [idea-iitd/graphgen#9]
Great work!
Thank you for uploading the code.
I replicated your fantastic code, and everything works fine except for the DGMG part.
Somehow it works fine when we use CPU mode.
But in GPU mode, we get the following errors.
___________________________________________
~/path/to/graphgen/baselines/dgmg/model.py in forward(self, g_list)
     78         bg = dgl.batch(g_list)
     79         print("debug:", bg, "ndata:",bg.ndata)
---> 80         bhv = bg.ndata['hv']
     81         bg.ndata['hg'] = self.node_gating(bhv) * self.node_to_graph(bhv)
     82
~/anaconda3/lib/python3.7/site-packages/dgl/view.py in __getitem__(self, key)
     65             return ret
     66         else:
---> 67             return self._graph._get_n_repr(self._ntid, self._nodes)[key]
     68
     69     def __setitem__(self, key, val):
~/anaconda3/lib/python3.7/site-packages/dgl/frame.py in __getitem__(self, name)
    493             Column data.
    494         """
--> 495         return self._columns[name].data
    496
    497     def __setitem__(self, name, data):
KeyError: 'hv'
___________________________________________
I have been debugging this for ages, but in vain.
Do you have any suggestions on what might be the problem here?
Thank you in advance for your reply.

**Comment by rkondo3** [comment]
Thank you for your kind response.
I added print debug code like following snippet.

```baselines/dgmg/model.py
class DGMG(nn.Module):
    def __init__(self, v_max, node_hidden_size, num_prop_rounds,
        ...
        print("[DGMG][init]device:",  device)
        ...

class GraphEmbed(nn.Module):
    ...
    def forward(self, g_list):
        ...
        bg = dgl.batch(g_list)
        print("[GraphEmbed]bg:", bg, "ndata:",bg.ndata)
        bhv = bg.ndata['hv']
        ...

class AddNode(nn.Module):
    ...
    def _initialize_node_repr(self, g, node_type, graph_embed):
        num_nodes = g.number_of_nodes()
        hv_init = self.initialize_hv(
            torch.cat([
                self.node_type_embed(torch.LongTensor(
                    [node_type]).to(device=self.device)),
                graph_embed], dim=1))
        print("[AddNode][_initialize_node_repr]hv_init:", hv_init)
        g = g.to(device=self.device)
        g.nodes[num_nodes - 1].data['hv'] = hv_init.to(device=self.device)
        print("[AddNode][_initialize_node_repr]g.nodes[num_nodes - 1].data['hv']:", g.nodes[num_nodes - 1].data['hv'])
```

```before training
model = create_model(args, feature_map)
print("[model][is_cuda]", next(model['generator'].parameters()).is_cuda)
```

And the debug code returns following std outputs. 
```
[DGMG][init]device: cuda:0
[model][is_cuda]True
[AddNode][_initialize_node_repr]hv_init: tensor([[...]], device='cuda:0',grad_fn=<AddmmBackward0>)
[AddNode][_initialize_node_repr]g.nodes[num_nodes - 1].data['hv']: tensor([[...]], device='cuda:0',grad_fn=<IndexSelectBackward0>)
[GraphEmbed]bg: Graph(num_nodes=32, num_edges=0, ndata_schemes={}, edata_schemes={}) ndata: {}
```
According to the outputs, the value of key 'hv' must be on the device 'cuda:0'.
However, bg.ndata has not the key 'hv' in GraphEmbed. The value seems to disappear in the "forward()" process of GraphEmbed.
Do you have any ideas to debug this problem?

**Comment by harshvjain** [comment]
We have updated the main repository code to incorporate cuda compatibility. Please fetch the updates and close the issue if the error is resolved.

**Comment by rkondo3** [comment]
I'm very sorry for so late reply because of covid.
Thank you for updating! It's amazing! I finally checked the update with my code and data.
It successfully worked!
